using System.Runtime.InteropServices.JavaScript;
using System.Runtime.Versioning;

namespace DolphinLink.SerialPort.WebSerial;

/// <summary>
/// Low-level [JSImport] bindings for the <c>webserial-interop.js</c> ES module.
///
/// <para>
/// These methods are generated by the .NET JavaScript interop source generator
/// and must not be called until <see cref="JSHost.ImportAsync"/> has loaded the module.
/// Use <see cref="WebSerialPort.CreateAsync"/> to obtain a fully initialised
/// <see cref="WebSerialPort"/>; it handles module loading automatically.
/// </para>
///
/// <para>
/// All methods on this class are internal — callers should go through
/// <see cref="WebSerialPort"/> and <see cref="WebSerialHelpers"/>.
/// </para>
///
/// <para>
/// <b>Data delivery design:</b> <c>byte[]</c> cannot be used as a generic parameter of
/// <c>JSType.Function</c>, so a delegate-based callback approach is not viable for
/// delivering received bytes.  Instead, the JS read pump calls back to .NET via the
/// <see cref="OnData"/> <c>[JSExport]</c> static method.  The JS module discovers this
/// method at startup via <c>getAssemblyExports</c>.  A per-port dispatch table
/// (<see cref="RegisterCallback"/> / <see cref="UnregisterCallback"/>) routes each
/// call to the correct <see cref="WebSerialStream"/>.
/// </para>
/// </summary>
[SupportedOSPlatform("browser")]
internal static partial class WebSerialInterop
{
    /// <summary>
    /// The module identifier used in <c>[JSImport]</c> attributes — must match the first
    /// argument passed to <see cref="JSHost.ImportAsync"/>.
    /// </summary>
    internal const string ModuleName = "_content/DolphinLink.SerialPort.WebSerial/webserial-interop.js";

    /// <summary>
    /// The relative URL the browser fetches when loading the module.
    /// Resolved against <c>document.baseURI</c> (set from <c>&lt;base href&gt;</c>) by the
    /// WASM runtime, so it works correctly regardless of the deployment sub-path
    /// (e.g. <c>/DolphinLink/</c> on GitHub Pages or <c>/</c> in local dev).
    /// </summary>
    internal const string ModuleUrl = "_content/DolphinLink.SerialPort.WebSerial/webserial-interop.js";

    // -------------------------------------------------------------------------
    // JS → .NET data delivery dispatch table
    // -------------------------------------------------------------------------

    // Keyed by portId.  Each entry receives each inbound chunk (or an empty array = EOF).
    // Access is single-threaded (WASM cooperative), so no locking needed.
    private static readonly Dictionary<int, Action<byte[]>> _callbacks = new();

    /// <summary>
    /// Registers the data-delivery callback for the given port handle.
    /// Called by <see cref="WebSerialStream"/> before <see cref="StartReadingJs"/> is invoked.
    /// </summary>
    internal static void RegisterCallback(int portId, Action<byte[]> callback)
        => _callbacks[portId] = callback;

    /// <summary>
    /// Removes the data-delivery callback for the given port handle.
    /// Called by <see cref="WebSerialStream.DisposeAsync"/> during cleanup.
    /// </summary>
    internal static void UnregisterCallback(int portId)
        => _callbacks.Remove(portId);

    /// <summary>
    /// [JSExport] entry point called by the JS read pump for every received chunk.
    ///
    /// <para>
    /// An <b>empty</b> <paramref name="data"/> array (<c>new Uint8Array(0)</c> on the JS side)
    /// signals EOF or a stream error — the JS pump never delivers genuinely empty chunks
    /// from a WebSerial <c>ReadableStream</c>.
    /// </para>
    /// </summary>
    [JSExport]
    internal static void OnData(int portId, byte[] data)
    {
        if (_callbacks.TryGetValue(portId, out var cb))
        {
            cb(data);
        }
    }

    // -------------------------------------------------------------------------
    // [JSImport] bindings — one per JS export in webserial-interop.js
    // -------------------------------------------------------------------------

    /// <summary>
    /// Initialises the JS module by resolving the <see cref="OnData"/> [JSExport] method
    /// from the given assembly.  Must be called once after
    /// <see cref="JSHost.ImportAsync"/> and before <see cref="StartReadingJs"/>.
    /// </summary>
    /// <param name="assemblyName">
    /// The assembly DLL file name, e.g. <c>"DolphinLink.SerialPort.WebSerial.dll"</c>.
    /// </param>
    [JSImport("initModule", ModuleName)]
    internal static partial Task InitModuleJs(string assemblyName);

    /// <summary>
    /// Returns <c>true</c> when the WebSerial API is available in the current browser context.
    /// </summary>
    [JSImport("isSupported", ModuleName)]
    internal static partial bool IsSupported();

    /// <summary>
    /// Shows the browser's serial port picker (optionally filtered by USB VID/PID),
    /// opens the selected port at the given baud rate, and returns an integer port handle.
    /// Returns <c>-1</c> if the user cancels or opening fails.
    /// </summary>
    /// <param name="usbVendorId">USB vendor ID filter, or <c>0</c> for no filter.</param>
    /// <param name="usbProductId">USB product ID filter, or <c>0</c> for no filter.</param>
    /// <param name="baudRate">Baud rate, e.g. 115200.</param>
    [JSImport("openPort", ModuleName)]
    internal static partial Task<int> OpenPortJs(int usbVendorId, int usbProductId, int baudRate);

    /// <summary>
    /// Starts the ReadableStream pump for the given port.
    ///
    /// <para>
    /// The JS pump calls <see cref="OnData"/> (a <c>[JSExport]</c> method) for each
    /// received chunk and once more with an empty array to signal EOF.  The JS side
    /// discovers <c>OnData</c> at startup via <c>getAssemblyExports</c>; no callback
    /// delegate is passed here.
    /// </para>
    /// </summary>
    [JSImport("startReading", ModuleName)]
    internal static partial void StartReadingJs(int portId);

    /// <summary>
    /// Writes <paramref name="data"/> to the given port's <c>WritableStream</c>.
    /// </summary>
    [JSImport("write", ModuleName)]
    internal static partial Task WriteJs(int portId, byte[] data);

    /// <summary>
    /// Sets the DTR modem control signal on the given port.
    /// </summary>
    [JSImport("setSignals", ModuleName)]
    internal static partial Task SetSignalsJs(int portId, bool enabled);

    /// <summary>
    /// Closes the given port and releases OS-level resources, but keeps the browser's
    /// permission grant so the port still appears in <c>navigator.serial.getPorts()</c>.
    /// Safe to call multiple times.
    /// </summary>
    [JSImport("closePort", ModuleName)]
    internal static partial Task ClosePortJs(int portId);

    /// <summary>
    /// Closes the given port AND revokes the browser's permission grant, completely
    /// removing it from <c>navigator.serial.getPorts()</c> and releasing all OS-level
    /// claims.
    ///
    /// <para>
    /// Use this instead of <see cref="ClosePortJs"/> when the port must be fully
    /// released so that the Flipper's USB stack can re-enumerate (e.g. before the
    /// daemon FAP switches from <c>usb_cdc_single</c> to <c>usb_cdc_dual</c>).
    /// </para>
    ///
    /// <para>
    /// <c>SerialPort.forget()</c> was added in Chrome 103.  On older browsers the close
    /// still succeeds; the forget step is skipped silently.
    /// </para>
    /// </summary>
    [JSImport("forgetPort", ModuleName)]
    internal static partial Task ForgetPortJs(int portId);

    /// <summary>
    /// Returns a JSON-encoded array of port handle IDs for all previously-granted serial
    /// ports matching the given USB VID/PID filter, opening each one at
    /// <paramref name="baudRate"/>.  Ports that are already tracked or that cannot be
    /// opened are silently skipped.
    ///
    /// <para>
    /// The return value is a JSON string (e.g. <c>"[1,2]"</c>) because the
    /// JSImport source generator does not support <c>Task&lt;int[]&gt;</c>.
    /// Use <see cref="System.Text.Json.JsonSerializer"/> to deserialise.
    /// </para>
    ///
    /// <para>
    /// Does <b>not</b> require a user gesture — suitable for polling after a USB
    /// re-enumeration without waiting for a button click.
    /// </para>
    ///
    /// <para>
    /// Each returned handle must eventually be passed to <see cref="ClosePortJs"/>
    /// when it is no longer needed.
    /// </para>
    /// </summary>
    /// <param name="usbVendorId">USB vendor ID filter, or <c>0</c> for no filter.</param>
    /// <param name="usbProductId">USB product ID filter, or <c>0</c> for no filter.</param>
    /// <param name="baudRate">Baud rate used when opening each port.</param>
    /// <returns>JSON array string of port handle IDs (e.g. <c>"[]"</c> or <c>"[1,2]"</c>).</returns>
    [JSImport("getPorts", ModuleName)]
    internal static partial Task<string> GetPortsJs(int usbVendorId, int usbProductId, int baudRate);
}
