/**
 * daemon_info.c — daemon_info command handler implementation
 *
 * Returns a fixed descriptor block: daemon name, protocol version, and the
 * full list of command names from the generated dispatch table.
 * The host uses this response for capability negotiation (detect whether a
 * specific command is supported before calling it).
 *
 * COMMAND_NAMES[] and CMD_COUNT are generated by codegens/c-codegen.csx into
 * rpc_dispatch_generated.h — they always stay in sync with the dispatch table.
 */

#include "daemon_info.h"
#include "../../core/rpc_response.h"
#include "../../core/rpc_cmd_log.h"
#include "../../generated/rpc_dispatch_generated.h"

#include <furi.h>
#include <stdio.h>
#include <inttypes.h>

void daemon_info_handler(uint32_t id, const char* json) {
    UNUSED(json);

    /*
     * Build the response in a single buffer.  Capacity breakdown:
     *   Header:        ~50 bytes
     *   commands array: CMD_COUNT * ~30 bytes worst-case ≈ 1400
     *   Footer:         10 bytes
     *   Total budget:  1536 bytes (safe).
     */
    char resp[1536];
    int pos = 0;

    pos += snprintf(
        resp + pos,
        (int)sizeof(resp) - pos,
        "{\"n\":\"flipper_zero_rpc_daemon\","
        "\"v\":%d,"
        "\"cmds\":[",
        DAEMON_PROTOCOL_VERSION);

    for(size_t i = 0; i < CMD_COUNT; i++) {
        bool last = (i == CMD_COUNT - 1);
        pos += snprintf(
            resp + pos,
            (int)sizeof(resp) - pos,
            "\"%s\"%s",
            COMMAND_NAMES[i],
            last ? "" : ",");
    }

    pos += snprintf(resp + pos, (int)sizeof(resp) - pos, "]}");
    UNUSED(pos);

    char log_entry[CMD_LOG_LINE_LEN];
    snprintf(
        log_entry,
        sizeof(log_entry),
        "#%" PRIu32 " daemon_info -> ok (%zu cmds)",
        id,
        (size_t)CMD_COUNT);

    rpc_send_data_response(id, resp, log_entry);
}

