/**
 * rpc_dispatch.c — RPC command registry and dispatcher implementation
 */

#include "rpc_dispatch.h"
#include "rpc_json.h"
#include "rpc_response.h"
#include "rpc_resource.h"
#define RPC_DISPATCH_IMPL
#include "../generated/rpc_dispatch_generated.h"

#include <furi.h>
#include <string.h>

/* -------------------------------------------------------------------------
 * Dispatcher — V1 wire format
 *
 * Requests use integer command IDs:
 *   {"c":<cmd_id>,"i":<request_id>,...args...}
 * The commands[] table and COMMAND_NAMES[] are generated by c-codegen.csx
 * and included above via RPC_DISPATCH_IMPL.
 * ------------------------------------------------------------------------- */

void rpc_dispatch(const char* json) {
    uint32_t request_id = 0;
    uint32_t cmd_id = 0;

    /* Extract "i" (request id) then "c" (command id) */
    const char* cursor = json;
    json_extract_uint32_at(json, &cursor, "i", &request_id);

    if(!json_extract_uint32_at(json, &cursor, "c", &cmd_id)) {
        rpc_send_error(request_id, "missing_cmd", "???");
        return;
    }

    if(cmd_id >= CMD_COUNT) {
        rpc_send_error(request_id, "unknown_command", "???");
        return;
    }

    const char* cmd_name = COMMAND_NAMES[cmd_id];
    FURI_LOG_I("RPC", "cmd=%s(%"PRIu32") id=%"PRIu32, cmd_name, cmd_id, request_id);

    const RpcCommand* cmd = &commands[cmd_id];
    if(cmd->resources && !resource_can_acquire(cmd->resources)) {
        rpc_send_error(request_id, "resource_busy", cmd_name);
        return;
    }
    cmd->handler(request_id, json);
}
