/**
 * rpc_dispatch.c — RPC command registry and dispatcher implementation
 */

#include "rpc_dispatch.h"
#include "rpc_json.h"
#include "rpc_response.h"
#include "rpc_resource.h"
#include "rpc_metrics.h"
#define RPC_DISPATCH_IMPL
#include "../generated/rpc_dispatch_generated.h"

#include <furi.h>

/* -------------------------------------------------------------------------
 * Dispatcher — V1 wire format
 *
 * Requests arrive as compact JSON (no whitespace):
 *   {"c":<cmd_id>,"i":<request_id>,...args...}
 * Fields are parsed in wire order using json_find() with offset hints so
 * each field is found with a single forward scan — no snprintf, no strstr.
 * The commands[] table and COMMAND_NAMES[] are generated by c-codegen.csx
 * and included above via RPC_DISPATCH_IMPL.
 * ------------------------------------------------------------------------- */

void rpc_dispatch(const char* json) {
    JsonValue val;
    uint32_t cmd_id = 0;
    uint32_t request_id = 0;
    size_t hint = 0;

    if(metrics_enabled) g_metrics.t_start = furi_get_tick();

    /* "c" is first on the wire: {"c":<id>,...} */
    if(!json_find(json, "c", hint, &val) || !json_value_uint32(&val, &cmd_id)) {
        rpc_send_error(0, "missing_cmd", "???");
        return;
    }
    hint = val.offset;

    /* "i" is second on the wire: {"c":N,"i":<id>,...} */
    if(json_find(json, "i", hint, &val)) {
        json_value_uint32(&val, &request_id);
        hint = val.offset;
    }

    if(metrics_enabled) g_metrics.t_parsed = furi_get_tick();

    if(cmd_id >= CMD_COUNT) {
        rpc_send_error(request_id, "unknown_command", "???");
        return;
    }

    const char* cmd_name = COMMAND_NAMES[cmd_id];
    FURI_LOG_I("RPC", "cmd=%s(%" PRIu32 ") id=%" PRIu32, cmd_name, cmd_id, request_id);

    const RpcCommand* cmd = &commands[cmd_id];
    if(cmd->resources && !resource_can_acquire(cmd->resources)) {
        rpc_send_error(request_id, "resource_busy", cmd_name);
        return;
    }

    if(metrics_enabled) g_metrics.t_dispatched = furi_get_tick();
    cmd->handler(request_id, json, hint);
}

