// Hand-written partial — lookup tables are in Generated/RpcJsonNormalizer.g.cs
// which is produced by running: dotnet script codegens/normalizer-codegen.csx
#nullable enable

using System.Buffers;
using System.Text;

namespace DolphinLink.Client;

/// <summary>
/// Transforms compact wire-format NDJSON into human-readable JSON for diagnostics
/// and logging.  Expands abbreviated wire keys to full names, resolves integer enum
/// values to named constants, converts numeric booleans (1/0) to true/false, and
/// maps command IDs to command names.
/// </summary>
/// <remarks>
/// This class is split across two files:
/// <list type="bullet">
///   <item><description>
///     <c>Generated/RpcJsonNormalizer.g.cs</c> — generated by
///     <c>codegens/normalizer-codegen.csx</c>; contains all private lookup switch
///     expressions (<c>CommandIdToName</c>, <c>ExpandRequestKey</c>, etc.).
///   </description></item>
///   <item><description>
///     <c>RpcJsonNormalizer.cs</c> (this file) — hand-written; contains the
///     <see cref="Normalize"/> entry point and the JSON rewriting logic built on
///     <see cref="JsonDocument"/> and <see cref="Utf8JsonWriter"/>.
///   </description></item>
/// </list>
/// Direction is one-way: compact wire JSON → human-readable.  Unknown keys and
/// command IDs pass through verbatim.  Malformed input returns the original string.
/// </remarks>
public static partial class RpcJsonNormalizer
{
    private static readonly JsonWriterOptions WriterOptions = new() { Indented = false };

    /// <summary>
    /// Normalizes a single wire-format JSON line to human-readable form.
    /// </summary>
    /// <param name="rawJson">The compact JSON string from the wire.</param>
    /// <param name="commandName">
    /// Optional command name (e.g. <c>"gpio_read"</c>) used to expand payload
    /// keys and resolve enums.  When <c>null</c>, only envelope keys are expanded.
    /// </param>
    /// <returns>
    /// A human-readable JSON string, or the original string if the input is
    /// null/empty, not a JSON object, or malformed.
    /// </returns>
    public static string Normalize(string? rawJson, string? commandName = null)
    {
        if (string.IsNullOrEmpty(rawJson) || rawJson[0] != '{')
        {
            return rawJson ?? string.Empty;
        }

        try
        {
            using var doc = JsonDocument.Parse(rawJson);
            var root = doc.RootElement;
            if (root.ValueKind != JsonValueKind.Object)
            {
                return rawJson;
            }

            var buf = new ArrayBufferWriter<byte>();
            using var writer = new Utf8JsonWriter(buf, WriterOptions);
            WriteNormalized(writer, root, commandName);
            writer.Flush();
            return Encoding.UTF8.GetString(buf.WrittenSpan);
        }
        catch
        {
            return rawJson;
        }
    }

    // ─── Top-level rewriter ───────────────────────────────────────────────────

    private static void WriteNormalized(Utf8JsonWriter w, JsonElement root, string? commandName)
    {
        // Detect direction: requests have "c" as first key.
        bool isRequest = root.TryGetProperty("c", out _);

        // Pre-resolve command name and message type.
        string? resolvedCmd = commandName;
        int messageType = -1;

        if (isRequest && resolvedCmd == null && root.TryGetProperty("c", out var cEl)
            && cEl.TryGetInt32(out int cmdId))
        {
            resolvedCmd = DolphinLink.Client.RpcJsonNormalizer.CommandIdToName(cmdId);
        }

        if (!isRequest && root.TryGetProperty("t", out var tEl)
                       && tEl.TryGetInt32(out int mt))
        {
            messageType = mt;
        }

        w.WriteStartObject();

        foreach (var prop in root.EnumerateObject())
        {
            string wire = prop.Name;

            if (isRequest)
            {
                string humanKey = wire switch
                {
                    "c" => "command",
                    "i" => "id",
                    _   => DolphinLink.Client.RpcJsonNormalizer.ExpandRequestKey(resolvedCmd, wire) ?? wire,
                };
                w.WritePropertyName(humanKey);

                if (wire == "c")
                {
                    // Replace integer command ID with command name string.
                    if (resolvedCmd != null)
                    {
                        w.WriteStringValue(resolvedCmd);
                    }
                    else
                    {
                        prop.Value.WriteTo(w);
                    }
                }
                else if (wire == "i")
                {
                    prop.Value.WriteTo(w);
                }
                else
                {
                    WriteExpandedValue(w, prop.Value, resolvedCmd, wire, isRequest: true);
                }
            }
            else
            {
                string humanKey = wire switch
                {
                    "t"  => "type",
                    "i"  => messageType == 1 ? "stream_id" : "id",
                    "p"  => "payload",
                    "e"  => "error",
                    "_m" => "metrics",
                    _    => wire,
                };
                w.WritePropertyName(humanKey);

                if (wire == "t")
                {
                    string typeStr = messageType switch
                    {
                        0 => "response",
                        1 => "event",
                        2 => "disconnect",
                        _ => prop.Value.GetRawText(),
                    };
                    w.WriteStringValue(typeStr);
                }
                else if (wire == "p" && prop.Value.ValueKind == JsonValueKind.Object)
                {
                    WritePayloadObject(w, prop.Value, resolvedCmd);
                }
                else if (wire == "_m" && prop.Value.ValueKind == JsonValueKind.Object)
                {
                    WriteMetricsObject(w, prop.Value);
                }
                else
                {
                    prop.Value.WriteTo(w);
                }
            }
        }

        w.WriteEndObject();
    }

    // ─── Payload object ───────────────────────────────────────────────────────

    private static void WritePayloadObject(Utf8JsonWriter w, JsonElement obj, string? resolvedCmd)
    {
        w.WriteStartObject();
        foreach (var prop in obj.EnumerateObject())
        {
            string pkWire = prop.Name;
            // "s" with no command context → stream_id (stream-open response).
            // "s" in a response payload always means stream_id — no command response
            // uses "s" for any other purpose, regardless of whether we know the command name.
            string pkHuman = pkWire == "s"
                ? "stream_id"
                : DolphinLink.Client.RpcJsonNormalizer.ExpandResponseKey(resolvedCmd, pkWire) ?? pkWire;

            w.WritePropertyName(pkHuman);
            WriteExpandedValue(w, prop.Value, resolvedCmd, pkWire, isRequest: false);
        }
        w.WriteEndObject();
    }

    // ─── Metrics object ───────────────────────────────────────────────────────

    private static void WriteMetricsObject(Utf8JsonWriter w, JsonElement obj)
    {
        w.WriteStartObject();
        foreach (var prop in obj.EnumerateObject())
        {
            string mkHuman = prop.Name switch
            {
                "pr" => "parse",
                "dp" => "dispatch",
                "ex" => "execute",
                "sr" => "serialize",
                "tt" => "total",
                var k => k,
            };
            w.WritePropertyName(mkHuman);
            prop.Value.WriteTo(w);
        }
        w.WriteEndObject();
    }

    // ─── Value expansion ──────────────────────────────────────────────────────

    private static void WriteExpandedValue(
        Utf8JsonWriter w, JsonElement el, string? cmd, string wireKey, bool isRequest)
    {
        // Only integers need expansion; strings, arrays, nested objects pass through.
        if (el.ValueKind == JsonValueKind.Number && el.TryGetInt64(out long iv))
        {
            bool isBool = isRequest
                ? DolphinLink.Client.RpcJsonNormalizer.IsRequestBoolField(cmd, wireKey)
                : DolphinLink.Client.RpcJsonNormalizer.IsResponseBoolField(cmd, wireKey);

            if (isBool)
            {
                w.WriteBooleanValue(iv != 0);
                return;
            }

            string? label = isRequest
                ? DolphinLink.Client.RpcJsonNormalizer.ExpandRequestEnum(cmd, wireKey, iv)
                : DolphinLink.Client.RpcJsonNormalizer.ExpandResponseEnum(cmd, wireKey, iv);

            if (label != null)
            {
                w.WriteStringValue(label);
            }
            else
            {
                el.WriteTo(w);
            }
        }
        else
        {
            el.WriteTo(w);
        }
    }
}
